#!/bin/bash
## Author: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMLH703MTvBQotnbI51WMnFpi+ExjceBGFE5B3ix6EPz 3880336+KodeToad@users.noreply.github.com

IGNORE="txt|srt|jpg|sub|png|xml|idx|nfo|parts|exe|url|zip|7z|rar|doc|docx|bak|sqlite|jpeg|log|m3u|cue|ini"

printf '\033[1;37m%8s %8s %s\033[0m\n' "inode" "size" "filename"
while read inode size file; do
    printf '%8s %8s %s\n' "$inode" "$(numfmt --to=iec $size)" "$file"
done < <( find . -xdev -regextype posix-egrep -iregex ".*\.($IGNORE)$" -prune -o \( -type f -links 1 -printf '%i %s %p\n' \) )
